version: '3.8'

services:

  docker:
    image: docker:latest
    ports:
      - 2375:2375

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: martinjsdev/smartservices:backend-last
    ports:
      - "8080:3000"
    env_file:
      - .env 
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/about.json"]
    #   interval: 30s
    #   retries: 3
    #   start_period: 30s
    #   timeout: 10s

  frontend:
    build:
      context: ./smart-services
      dockerfile: Dockerfile
    image: martinjsdev/smartservices:frontend-last
    ports:
      - "5173:5173"
    env_file:
      - .env