name: Continus Integration - [ React App ]

on:
    push:
        branches: staging
    pull_request:
        branches: staging

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                node-version: "latest"

            - name: Install dependencies
              run: npm install

            - name: Run link
              run: npm run link

            - name: Run tests
              run: npm test