name: Continus Integration

on:
    push:
        branches: staging
    pull_request:
        branches: staging

jobs:
    build:
        runs-on: ubuntu-latest

        services:
          docker:
            image: docker:latest
            ports:
              - 2375:2375
            options: --privileged

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: "latest"

            - name: Install Frontend dependencies
              run: |
                cd smart-services
                npm install

            - name: Install Backend Dependencies
              run: |
                cd backend
                npm install

                
            - name: Run link
              run: |
                cd smart-services
                npm run link
                cd ../backend
                npm run link

                
            - name: Run tests
              run: |
                cd smart-services
                npm test
                cd ../backend
                npm test

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Install Docker Compose
              run: sudo apt-get install docker-compose

            - name: Build and Test with Docker Compose
              run: |
                docker-compose -f docker-compose.yml build
                docker-compose -f docker-compose.yml up -d
                curl -f http://localhost:8081/about.json
                docker-compose -f docker-compose.yml down