name: Sync to a private repos

on:
    push:
        branches: 
            - main

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the private repos
              uses: actions/checkout@v3

            - name: Set up SSH key
              run: |
                mkdir -p ~/.ssh
                